# docker run -p 9090:9090 -v /tmp/prometheus.yml:/etc/prometheus/prometheus.yml \
#       prom/prometheus
# 
#
# Don't run it like the above example.   If you use external files, they 
# won't be seen.  
#
# docker run -d -p 9090:9090 -v /media/docker/prometheus:/etc/prometheus/ prom/prometheus
