#  docker run -d -p 3000:3000 grafana/grafana
#
#
# docker run -d p 3000:3000 -name grafana -v /media/docker/grafana/etc:/etc/grafanac  \
# -v /media/docker/grafana/storage:/var/lib/grafana \
# grafana/grafana
