# sudo docker run --detach \
#    --hostname gitlab.example.com \
#    --publish 443:443 --publish 80:80 --publish 7999:22 \
#    --name gitlab \
#    --restart always \
#    --volume /media/docker/gitlab/config:/etc/gitlab \
#    --volume /media/docker/gitlab/logs:/var/log/gitlab \
#    --volume /media/docker/gitlab/data:/var/opt/gitlab \
#    gitlab/gitlab-ce:latest
