# sudo docker run --detach \
#    --hostname gitlab.example.com \
#    --publish 443:443 --publish 80:80 --publish 7999:22 \
#    --name gitlab \
#    --restart always \
#    --volume /media/docker/gitlab/config:/etc/gitlab \
#    --volume /media/docker/gitlab/logs:/var/log/gitlab \
#    --volume /media/docker/gitlab/data:/var/opt/gitlab \
#    gitlab/gitlab-ce:latest
#
version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "7999:22"
    env_file:
      - .env
      - .env_hostname
    volumes:
      - /media/docker/gitlab/config:/etc/gitlab
      - /media/docker/gitlab/logs:/var/log/gitlab 
      - /media/docker/gitlab/data:/var/opt/gitlab
