version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/New_York
        # https://www.plex.tv/claim/
      - PLEX_CLAIM=<get-the-code>
      - ADVERTISE_IP=http://XXX.XXX.XXX.XXX:32400/
    hostname: plex
    volumes:
      - /media/docker/plex/database:/config
      - /tmp:/transcode
      - /media/movies:/movies
      - /media/tv:/tv
      - /media/photos:/photos
      - /media/music:/music
